#include "semant.h"
#include "stringtab.h"

// 定义所有预定义的符号
Symbol arg;
Symbol arg2;
Symbol Bool;
Symbol concat;
Symbol cool_abort;
Symbol copy;
Symbol Int;
Symbol in_int;
Symbol in_string;
Symbol IO;
Symbol length;
Symbol Main;
Symbol main_meth;
Symbol No_class;
Symbol No_type;
Symbol Object;
Symbol out_int;
Symbol out_string;
Symbol prim_slot;
Symbol self;
Symbol SELF_TYPE;
Symbol Str;
Symbol str_field;
Symbol substr;
Symbol type_name;
Symbol val;